### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by tshemsedinov** [gapiyka/Reader#1]
1. I'd prefer to use collections instead of if-statements in casas like this: https://github.com/gapiyka/Reader/blob/c479e46281b365e91549a067765b6da3a8b16715/Assets/Scripts/InputHandler.cs#L19-L27
2. Id you use code block `{}` in `else` it is better to use it in positive if-branch too: https://github.com/gapiyka/Reader/blob/c479e46281b365e91549a067765b6da3a8b16715/Assets/Scripts/OpenFileDialog.cs#L117-L120
3. Magic numbers anpipattern is not about only numbers, for example if you have hardcoded color or string in source without constant or any understandable nam
ing/identifying its also an issue to refactor
4. Long procedures like this should be decomposed https://github.com/gapiyka/Reader/blob/c479e46281b365e91549a067765b6da3a8b16715/Assets/Scripts/Parser.cs#L11-L53
5. Duplicate expressions, I'd prefer to put to intermediate variable: https://github.com/gapiyka/Reader/blob/c479e46281b365e91549a067765b6da3a8b16715/Assets/Scripts/Parser.cs#L25
6. Project have a small and not complex codebase

**Comment by tshemsedinov** [comment]
You have 83

**Comment by gapiyka** [comment]
> Magic numbers anpipattern is not about only numbers, for example if you have hardcoded color or string in source without constant or any understandable nam
ing/identifying its also an issue to refactor

Yeah, magic numbers and hardcoded parts - are one of my weak sides ;(

Other notes (except **6th**) will be updated in next commit <3

Thanks for your video-lectures @tshemsedinov

**Comment by gapiyka** [comment]
update commit: https://github.com/gapiyka/Reader/commit/a9cb626ec167538543efef5a04f3535c0be54a0a
